server:
  port: 8083

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/**